AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  deathbyai

  SAM Template for Death by AI game

Globals:
  Function:
    Timeout: 10
    MemorySize: 128
    Runtime: go1.x
    Architectures:
      - x86_64
    Environment:
      Variables:
        GAMES_TABLE: !Ref GamesTable

Resources:
  CreateGameFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: games/
      Handler: main.go
      Events:
        CreateGame:
          Type: Api
          Properties:
            Path: /games
            Method: POST
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref GamesTable

  GamesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: DeathByAIGames
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: GameId
          AttributeType: S
      KeySchema:
        - AttributeName: GameId
          KeyType: HASH

Outputs:
  CreateGameAPI:
    Description: API Gateway endpoint URL for Prod environment for Create Game Function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/games/"
  CreateGameFunction:
    Description: Create Game Lambda Function ARN
    Value: !GetAtt CreateGameFunction.Arn
  CreateGameFunctionIamRole:
    Description: Implicit IAM Role created for Create Game function
    Value: !GetAtt CreateGameFunctionRole.Arn
  GamesTableName:
    Description: Name of the DynamoDB table for storing games
    Value: !Ref GamesTable